# Generated by Django 2.2.19 on 2022-08-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recieps', to='recipes.Tag', verbose_name='Теги'),
        ),
    ]
