# Generated by Django 2.2.19 on 2022-09-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220910_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recieps', to='recipes.Tag', verbose_name='Теги'),
        ),
    ]
