# Generated by Django 2.2.19 on 2022-09-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20220911_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'ordering': ['id'], 'verbose_name': 'Ингредиенты в рецептах', 'verbose_name_plural': 'Ингредиенты в рецептах'},
        ),
    ]
